apiVersion: apps/v1
kind: Deployment
metadata:
  name: testingdeploymentapp
  labels:
    app: testingApp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testingApp
  template:
    metadata:
      labels:
        app: testingApp
    spec:
      containers:
        - name: springecuritydeployment
          image: rgavhale/springecurity
          ports:
            - containerPort: 8034

